version: "3.8"
services:
  app:
    container_name: app
    build: ./
    command: ./segmenter
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=./configs/config.yaml
  db:
    container_name: postgres
    restart: always
    image: "postgres:16.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"